spring:
  datasource:
    url: jdbc:mysql://192.168.219.106:3306/fastcampus_db_batch?serverTimezone=UTC&characterEncoding=UTF-8
    username: fastcampus_user
    password: fastcampus
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    activate:
      on-profile: test

logging:
  level:
    org.hibernate.type.descriptor.sql : trace
