server:
  port: 8082

spring:
  application:
    name: pass-batch
  datasource:
    url: ${LOCAL_DB_MYSQL_URL}
    username: ${LOCAL_DB_MYSQL_USERNAME}
    password : ${LOCAL_DB_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      # minimum-idle: 20
  batch:
    jdbc:
      initialize-schema: always
